### PR TITLE
New invoice status "canceled" and "pre-payed" / storniert und Anzahlung

### PR DESCRIPTION
**Pull request by daking88**

### CODE REVIEW

**Comment by daking88** [comment]
@developeregrem what about this adjustment - or is it to specific?

**Comment by developeregrem** [comment]
Hi @daking88 its not to specific. I was just thinking to improve the statistics module accordingly.
What do you mean with "cancelled" is it an invoice for a cancelled reservation and you charge the cancellation fees?

**Comment by daking88** [comment]
Hi @developeregrem, in fact, we a creating invoices before the guests are arriving, because we want them to pay upfront. If, however, a booking is cancelled, I need to cancel the invoice as well - as otherwise, I wouldn't have a ongoing invoice number (one would be missing in between). Canellation fees is another topic, but I dun't know how to tackle this yet :)

**Comment by developeregrem** [comment]
Allrigth, makes sense! I will merge the request but also will add a filter to the turnover page in the statistics module to allow people to see the differences for the different status. Might be interesting for somebody :)

**Review by developeregrem — APPROVED** [review]

**Pull request merged**
